### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AndreyUA** [AndreyUA/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by AndreyZhigarev** [comment]
I'm not one to back away from a challenge!
Programming is my life, my calling and my art. I love it and that is why I work hard for the new skills with the newesttools and frameworks.

**Comment by AndreyUA** [comment]
Дякую!
