### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by AndreyUA** [AndreyUA/homepage#8]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by AndreyZhigarev** [comment]
https://www.facebook.com/andrey.andrey.92754397
https://www.instagram.com/andrey_zhygarev/
https://www.linkedin.com/in/andrey-zhygarev-62b1581b9/
