### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by AndreyUA** [AndreyUA/homepage#9]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by AndreyZhigarev** [comment]
Career
2014
I graduated from university at a difficult times and have no much oppotunities to choose a job. 
So I started my career as call-operator at government agency.

2015
Next step was to take a worthy position and I became an engineer. The work would have to be interesting and creative, 
though, and would not bring more revenue.
But my ideas crashed into bureaucratic hell.

2017
I got a chance and use it to become a part of pretty big IT company with my skills for that moment. 
Here I realised that programming is that thing I want to do for life.

2018
Completed courses "HTML. Basic JavaScript".

2019
Pored over a textbook learn.javascript.ru.

2020
Courses:
Node JS. Practical course: (Mongo, GraphQL, MySQL, Express)
React JS. Practical course: (Hooks, Classes, Redux)
MERN Stack Front To Back: Full Stack React, Redux & Node.js

First commercial expirience with barbershop site I shared with my friends. 

Education

1998-2008
Studied at the school #

2008-2014
University of shipbuilding named by admiral Makarov, Marine instrumentation department.

Privat life

2013-present time
All this time I devote my leisure to sports. Pumping iron is the best way to relax.

2017
Got married with my sweet wife.

2019
My wonderful son was born and gave me new motivation to make our life better.
